### ISSUE TITLE
Cant install pi-suite

### ISSUE THREAD

**Issue by theDiverDK** [reelyactive/pi-suite#2]
Tried to follow this guide:
https://reelyactive.github.io/make-a-pi-hub.html
But it fails at this:

```
mkdir ~/reelyActive
cd ~/reelyActive
git clone https://github.com/reelyactive/pi-suite.git
cd pi-suite
npm install
```

I get these errors at the 'npm install' part

```
pi@raspberrypi:~/reelyActive/pi-suite $ npm install

> usb@1.2.0 install /home/pi/reelyActive/pi-suite/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@6.11.2 (node-v48 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/reelyActive/pi-suite/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
libusb.target.mk:131: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/pi/reelyActive/pi-suite/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/local/node/bin/node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding"
gyp ERR! cwd /home/pi/reelyActive/pi-suite/node_modules/usb
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node/bin/node /usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/reelyActive/pi-suite/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.9.35-v7+
node-pre-gyp ERR! command "/usr/local/node/bin/node" "/home/pi/reelyActive/pi-suite/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/reelyActive/pi-suite/node_modules/usb
node-pre-gyp ERR! node -v v6.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/node/bin/node /usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/reelyActive/pi-suite/node_modules/usb/src/binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
pi@raspberrypi:~/reelyActive/pi-suite $

```

Please help, i would love to use this software :)

**Comment by jeffyactive** [comment]
Although the errors and warnings look scary, the install is probably in fact okay.  As you can see in the final three lines, the usb package is an OPTIONAL DEPENDENCY.

Suggest you continue with the installation instructions for pi-suite and see if it all works out.

An alternative is to use the disk image we provide at https://reelyactive.github.io/make-a-pi-hub.html and transfer it to a fresh SD card for the Pi.  That image has everything pre-installed.

Please confirm if you're able to proceed and we'll close the issue (or solve any outstanding problems first).

**Comment by theDiverDK** [comment]
Thanks for the feedback.

I'll try to see if it does work, or try the image :)
