### ISSUE TITLE
pi-suite failing on pi zero w

### ISSUE THREAD

**Issue by jmiller0** [reelyactive/pi-suite#4]
Followed the tutorial, getting the following error starting pi-suite.

i@raspberrypi:~/reelyActive/pi-suite $ sudo node pi-suite
/home/pi/reelyActive/pi-suite/node_modules/hlc-server/node_modules/barnacles/node_modules/socket.io/node_modules/debug/src/node.js:132
        let val = process.env[key];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/reelyActive/pi-suite/node_modules/hlc-server/node_modules/barnacles/node_modules/socket.io/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

$ node --version
v4.8.2

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by jeffyactive** [comment]
Hi @jmiller0,

It looks like the socket.io package expects Node version 6 or 8.  If that's the case, there are at least two options:

1. update to a later version of Node (take care that it is supported on the Pi Zero W which is different than the Pi 3B)
2. force an install of an earlier version of socket.io (ex: npm install socket.io@2.0.0)

We're currently updating all the reelyActive OSS to the latest JavaScript best practices which will require Node 6 or later, so the first option would be recommended longer term, the first would be a quick fix.

Please advise if either/both do the trick so that the workaround is validated and documented.  Thanks!
